spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agreement_system
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 20MB
jwt:
  secret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  expiration: 86400000